spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: create
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug